version: 2
updates:
- package-ecosystem: gomod
  directories:
    - "/"
  schedule:
    interval: daily
  rebase-strategy: disabled
  commit-message:
      prefix: ":seedling:"
  open-pull-requests-limit: 3
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
  rebase-strategy: disabled
  commit-message:
      prefix: ":seedling:"
  groups:
    github-actions:
      patterns:
        - "*"
      # These actions directly influence the build process and are excluded from grouped updates
      exclude-patterns:
        - "actions/setup-go"
        - "goreleaser/goreleaser-action"
