coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch:
      default:
        target: 60%
        threshold: 1%

  ignore:
    - "cmd/**/*"
    - "gen/**/*" # generated code
    - "pkg/graph/mockGraph.go" # mockGraph is not covered
