name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb # v2
      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v2
        with:
          go-version: '1.23'
      - name: Install Wire
        run: |
          go install github.com/google/wire/cmd/wire@latest
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
      - name: Build
        run: make build && make git-porcelain

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb # v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      - name: Docker
        run: make docker-build && make git-porcelain
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb # v2
      - name: Check
        run: make git-porcelain go-mod-tidy

  test:
    runs-on: ubuntu-latest
    needs: [build, docker]
    steps:
      - name: Checkout code
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb # v2
      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v2
        with:
          go-version: '1.23'
      - name: Docker Up
        run: make docker-up
      - name: Test
        run: make test-e2e
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5c47607acb93fed5485fdbf7232e8a31425f672a # v5.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          verbose: true